resource_types:
- name: ubuntu
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/ubuntu-ruby-aws
    tag: latest

jobs:
- name: stemcells
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: stemcells
    file: pcf-info-repo/ci/tasks/stemcell/task.yml
    params:
      PCF_ENVIRONMENT: {{pcf_environment}}
      OPSMAN_USERNAME: {{opsman_admin}}
      OPSMAN_PASSWORD: {{opsman_password}}
      OPSMAN_URI: {{opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: available-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: available-products
    file: pcf-info-repo/ci/tasks/available-products/task.yml
    params:
      PCF_ENVIRONMENT: {{pcf_environment}}
      OPSMAN_USERNAME: {{opsman_admin}}
      OPSMAN_PASSWORD: {{opsman_password}}
      OPSMAN_URI: {{opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: deployed-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: deployed-products
    file: pcf-info-repo/ci/tasks/deployed-products/task.yml
    params:
      PCF_ENVIRONMENT: {{pcf_environment}}
      OPSMAN_USERNAME: {{opsman_admin}}
      OPSMAN_PASSWORD: {{opsman_password}}
      OPSMAN_URI: {{opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: staged-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: staged-products
    file: pcf-info-repo/ci/tasks/staged-products/task.yml
    params:
      PCF_ENVIRONMENT: {{pcf_environment}}
      OPSMAN_USERNAME: {{opsman_admin}}
      OPSMAN_PASSWORD: {{opsman_password}}
      OPSMAN_URI: {{opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: current-certs
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: current-certs
    file: pcf-info-repo/ci/tasks/certs/task.yml
    params:
      PCF_ENVIRONMENT: {{pcf_environment}}
      OPSMAN_USERNAME: {{opsman_admin}}
      OPSMAN_PASSWORD: {{opsman_password}}
      OPSMAN_URI: {{opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: grok-failures
  plan:
  - get: 1h
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: grok-failures
    file: pcf-info-repo/ci/tasks/elk-search/task.yml
    params:
      GROK_ENDPOINT: {{grok_endpoint}}

resources:
- name: pcf-info-repo
  type: git
  source:
    uri: ssh://git@ssh.github.com:443/aaa-ncnu-ie/pcf_info.git
    branch: master
    private_key: {{github_private_key}}
- name: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
  type: time
  source:
    start: {{scheduler-time-window-start}}
    stop: {{scheduler-time-window-stop}}
    location: {{scheduler-time-location}}
- name: 1h
  type: time
  source: {interval: 1h}
