resource_types:
- name: ubuntu
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/ubuntu-ruby-aws
    tag: latest

groups:
  - name: PDC-Info
    jobs:
      - pdc-stemcells
      - pdc-available-products
      - pdc-deployed-products
      - pdc-staged-products
      - pdc-current-certs
      - pdc-grok-failures

  - name: GDC-Info
    jobs:
      - gdc-stemcells
      - gdc-available-products
      - gdc-deployed-products
      - gdc-staged-products
      - gdc-current-certs

  - name: Sandbox-Info
    jobs:
      - sandbox-stemcells
      - sandbox-available-products
      - sandbox-deployed-products
      - sandbox-staged-products
      - sandbox-current-certs

jobs:
- name: pdc-stemcells
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: stemcells
    file: pcf-info-repo/ci/tasks/stemcell/task.yml
    params:
      PCF_ENVIRONMENT: {{pdc-pcf_environment}}
      OPSMAN_USERNAME: {{pdc-opsman_admin}}
      OPSMAN_PASSWORD: {{pdc-opsman_password}}
      OPSMAN_URI: {{pdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: pdc-available-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: available-products
    file: pcf-info-repo/ci/tasks/available-products/task.yml
    params:
      PCF_ENVIRONMENT: {{pdc-pcf_environment}}
      OPSMAN_USERNAME: {{pdc-opsman_admin}}
      OPSMAN_PASSWORD: {{pdc-opsman_password}}
      OPSMAN_URI: {{pdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: pdc-deployed-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: deployed-products
    file: pcf-info-repo/ci/tasks/deployed-products/task.yml
    params:
      PCF_ENVIRONMENT: {{pdc-pcf_environment}}
      OPSMAN_USERNAME: {{pdc-opsman_admin}}
      OPSMAN_PASSWORD: {{pdc-opsman_password}}
      OPSMAN_URI: {{pdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: pdc-staged-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: staged-products
    file: pcf-info-repo/ci/tasks/staged-products/task.yml
    params:
      PCF_ENVIRONMENT: {{pdc-pcf_environment}}
      OPSMAN_USERNAME: {{pdc-opsman_admin}}
      OPSMAN_PASSWORD: {{pdc-opsman_password}}
      OPSMAN_URI: {{pdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: pdc-current-certs
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: current-certs
    file: pcf-info-repo/ci/tasks/certs/task.yml
    params:
      PCF_ENVIRONMENT: {{pdc-pcf_environment}}
      OPSMAN_USERNAME: {{pdc-opsman_admin}}
      OPSMAN_PASSWORD: {{pdc-opsman_password}}
      OPSMAN_URI: {{pdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: pdc-grok-failures
  plan:
  - get: 1h
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: grok-failures
    file: pcf-info-repo/ci/tasks/elk-search/task.yml
    params:
      GROK_ENDPOINT: {{pdc-grok_endpoint}}

- name: gdc-stemcells
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: stemcells
    file: pcf-info-repo/ci/tasks/stemcell/task.yml
    params:
      PCF_ENVIRONMENT: {{gdc-pcf_environment}}
      OPSMAN_USERNAME: {{gdc-opsman_admin}}
      OPSMAN_PASSWORD: {{gdc-opsman_password}}
      OPSMAN_URI: {{gdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: gdc-available-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: available-products
    file: pcf-info-repo/ci/tasks/available-products/task.yml
    params:
      PCF_ENVIRONMENT: {{gdc-pcf_environment}}
      OPSMAN_USERNAME: {{gdc-opsman_admin}}
      OPSMAN_PASSWORD: {{gdc-opsman_password}}
      OPSMAN_URI: {{gdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: gdc-deployed-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: deployed-products
    file: pcf-info-repo/ci/tasks/deployed-products/task.yml
    params:
      PCF_ENVIRONMENT: {{gdc-pcf_environment}}
      OPSMAN_USERNAME: {{gdc-opsman_admin}}
      OPSMAN_PASSWORD: {{gdc-opsman_password}}
      OPSMAN_URI: {{gdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: gdc-staged-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: staged-products
    file: pcf-info-repo/ci/tasks/staged-products/task.yml
    params:
      PCF_ENVIRONMENT: {{gdc-pcf_environment}}
      OPSMAN_USERNAME: {{gdc-opsman_admin}}
      OPSMAN_PASSWORD: {{gdc-opsman_password}}
      OPSMAN_URI: {{gdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: gdc-current-certs
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: current-certs
    file: pcf-info-repo/ci/tasks/certs/task.yml
    params:
      PCF_ENVIRONMENT: {{gdc-pcf_environment}}
      OPSMAN_USERNAME: {{gdc-opsman_admin}}
      OPSMAN_PASSWORD: {{gdc-opsman_password}}
      OPSMAN_URI: {{gdc-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: sandbox-stemcells
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: stemcells
    file: pcf-info-repo/ci/tasks/stemcell/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: sandbox-available-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: available-products
    file: pcf-info-repo/ci/tasks/available-products/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: sandbox-deployed-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: deployed-products
    file: pcf-info-repo/ci/tasks/deployed-products/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: sandbox-staged-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: staged-products
    file: pcf-info-repo/ci/tasks/staged-products/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}

- name: sandbox-current-certs
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: current-certs
    file: pcf-info-repo/ci/tasks/certs/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}

resources:
- name: pcf-info-repo
  type: git
  source:
    uri: ssh://git@ssh.github.com:443/aaa-ncnu-ie/pcf_info.git
    branch: master
    private_key: {{github_private_key}}
- name: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
  type: time
  source:
    start: {{scheduler-time-window-start}}
    stop: {{scheduler-time-window-stop}}
    location: {{scheduler-time-location}}
- name: 1h
  type: time
  source: {interval: 1h}
