resource_types:
- name: ubuntu
  type: docker-image
  source:
    repository: smarshops/pcf-docker-container
    tag: latest

groups:
  - name: prod-Info
    jobs:
      - prod-stemcells
      - prod-available-products
      - prod-deployed-products
      - prod-staged-products
      - prod-current-certs
      - prod-grok-failures

  - name: GDC-Info
    jobs:
      - gdc-stemcells
      - gdc-available-products
      - gdc-deployed-products
      - gdc-staged-products
      - gdc-current-certs

  - name: Sandbox-Info
    jobs:
      - sandbox-stemcells
      - sandbox-available-products
      - sandbox-deployed-products
      - sandbox-staged-products
      - sandbox-current-certs

jobs:
- name: prod-stemcells
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: stemcells
    file: pcf-info-repo/ci/tasks/stemcell/task.yml
    params:
      PCF_ENVIRONMENT: {{prod-pcf_environment}}
      OPSMAN_USERNAME: {{prod-opsman_admin}}
      OPSMAN_PASSWORD: {{prod-opsman_password}}
      OPSMAN_URI: {{prod-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}
      S3_BUCKET: {{s3_bucket}}

- name: prod-available-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: available-products
    file: pcf-info-repo/ci/tasks/available-products/task.yml
    params:
      PCF_ENVIRONMENT: {{prod-pcf_environment}}
      OPSMAN_USERNAME: {{prod-opsman_admin}}
      OPSMAN_PASSWORD: {{prod-opsman_password}}
      OPSMAN_URI: {{prod-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}

- name: prod-deployed-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: deployed-products
    file: pcf-info-repo/ci/tasks/deployed-products/task.yml
    params:
      PCF_ENVIRONMENT: {{prod-pcf_environment}}
      OPSMAN_USERNAME: {{prod-opsman_admin}}
      OPSMAN_PASSWORD: {{prod-opsman_password}}
      OPSMAN_URI: {{prod-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}

- name: prod-staged-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: staged-products
    file: pcf-info-repo/ci/tasks/staged-products/task.yml
    params:
      PCF_ENVIRONMENT: {{prod-pcf_environment}}
      OPSMAN_USERNAME: {{prod-opsman_admin}}
      OPSMAN_PASSWORD: {{prod-opsman_password}}
      OPSMAN_URI: {{prod-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}

- name: prod-current-certs
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: current-certs
    file: pcf-info-repo/ci/tasks/certs/task.yml
    params:
      PCF_ENVIRONMENT: {{prod-pcf_environment}}
      OPSMAN_USERNAME: {{prod-opsman_admin}}
      OPSMAN_PASSWORD: {{prod-opsman_password}}
      OPSMAN_URI: {{prod-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}
      DATADOG_API_KEY: {{datadog_api_key}}

- name: prod-grok-failures
  plan:
  - get: 1h
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: grok-failures
    file: pcf-info-repo/ci/tasks/elk-search/task.yml
    params:
      GROK_ENDPOINT: {{prod-grok_endpoint}}

- name: sandbox-stemcells
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: stemcells
    file: pcf-info-repo/ci/tasks/stemcell/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}
      S3_BUCKET: {{s3_bucket}}

- name: sandbox-available-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: available-products
    file: pcf-info-repo/ci/tasks/available-products/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}

- name: sandbox-deployed-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: deployed-products
    file: pcf-info-repo/ci/tasks/deployed-products/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}

- name: sandbox-staged-products
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: staged-products
    file: pcf-info-repo/ci/tasks/staged-products/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      S3_BUCKET: {{s3_bucket}}

- name: sandbox-current-certs
  plan:
  - get: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
    trigger: true
  - get: pcf-info-repo
    trigger: false
  - task: current-certs
    file: pcf-info-repo/ci/tasks/certs/task.yml
    params:
      PCF_ENVIRONMENT: {{sandbox-pcf_environment}}
      OPSMAN_USERNAME: {{sandbox-opsman_admin}}
      OPSMAN_PASSWORD: {{sandbox-opsman_password}}
      OPSMAN_URI: {{sandbox-opsman_url}}
      AWS_ACCESS_KEY: {{aws_access_key}}
      AWS_SECRET_KEY: {{aws_secret_key}}
      DATADOG_API_KEY: {{datadog_api_key}}
      S3_BUCKET: {{s3_bucket}}

resources:
- name: pcf-info-repo
  type: git
  source:
    uri: ssh://git@ssh.github.com:443/aaa-ncnu-ie/pcf_info.git
    branch: master
    private_key: {{github_private_key}}
- name: scheduler {{scheduler-time-window-start}} to {{scheduler-time-window-stop}}
  type: time
  source:
    start: {{scheduler-time-window-start}}
    stop: {{scheduler-time-window-stop}}
    location: {{scheduler-time-location}}
- name: 1h
  type: time
  source: {interval: 1h}
