---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: smarshops/pcf-docker-container
    tag: latest

inputs:
  - name: pcf-info-repo

run:
  path: pcf-info-repo/ci/tasks/certs/current-certs.rb

params:
  params:
    OPSMAN_USERNAME:
    OPSMAN_PASSWORD:
    OPSMAN_URI:
