---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: smarshops/pcf-docker-container
    tag: latest

inputs:
  - name: pcf-info-repo

run:
  path: pcf-info-repo/ci/tasks/elk-search/grok-failures.rb

params:
  params:
    grok_endpoint:
